# Generated by Django 4.2.4 on 2023-09-22 06:49

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='change_date',
            field=models.DateTimeField(default=catalog.models.default_datetime, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(default=catalog.models.default_datetime, verbose_name='Дата создания'),
        ),
    ]
